import type { IndustryPage } from "./industries";

/**
 * Industry landing pages. Obligations come from the industry research checked
 * on 2026-10-02 against regulators' own publications where available; points
 * confirmed only by secondary sources are left out. Market practice is worded
 * as what buyers ask for, never as law. Only SOC 2 ships today: every other
 * framework library, and every module whose status in catalog.ts is "soon",
 * is described as coming soon. Workflows use live features only. Verity
 * organises the work; certification and attestation come from auditors and
 * certification bodies.
 */
export const industryPages: IndustryPage[] = [
  {
    slug: "banking-financial-services",
    eyebrow: "Banking and financial services",
    headline: "Ready for every inspection, and for the board's questions",
    lead: "Banks answer to supervisors, auditors and their own boards at once. Verity keeps controls, evidence, outsourcing arrangements, risk decisions and remediation in one connected record, each with an owner and a history, so an inspection request or a committee question is answered with a link, not a week of chasing.",
    audiences: [
      "Commercial and Islamic banks",
      "Microfinance banks",
      "Development finance institutions",
      "Insurers",
      "Central banks and regulators, for their own programmes",
    ],
    obligations: [
      {
        region: "pk",
        title: "48-hour incident reporting and board IT oversight",
        text: "Banks, microfinance banks and development finance institutions must report established cyber incidents to the State Bank of Pakistan within 48 hours. They must also run a Board IT Committee and an IT Steering Committee, and keep the CISO independent of IT.",
        source: "SBP ETGRMF, BPRD Circular No. 05 of 2017",
      },
      {
        region: "pk",
        title: "Board approval and a register for material outsourcing",
        text: "Material outsourcing needs board approval and an entry in the outsourcing register, and some offshore arrangements need the State Bank's prior approval. Running material workloads on offshore cloud needs its approval case by case.",
        source: "SBP BPRD Circular No. 06 of 2017 (amended 2019); BPRD Circular No. 01 of 2023",
      },
      {
        region: "ae",
        title: "Notify CBUAE within four hours of a critical event",
        text: "Since 14 September 2026, licensed financial institutions must notify the Central Bank of the UAE within four hours of an operational-risk event affecting critical operations, with a summary within 24 hours. Banks also keep an outsourcing register and need CBUAE non-objection before material outsourcing.",
        source: "CBUAE Circular No. 1/2026 (Operational Risk); Circular No. 14/2021 (Outsourcing)",
      },
      {
        region: "au",
        title: "72-hour notifications and a yearly provider register",
        text: "APRA-regulated entities must notify APRA within 72 hours of material information security incidents (CPS 234) and material operational-risk incidents (CPS 230), and submit a register of material service providers each year. APRA's independent CPS 234 reviews found board cyber reporting was often not fit for purpose.",
        source: "APRA CPS 234 and CPS 230",
      },
      {
        region: "us",
        title: "Several incident clocks at once",
        text: "Banks notify their primary federal regulator within 36 hours of a notification incident, NYDFS licensees notify NYDFS within 72 hours, and listed companies file a Form 8-K within four business days of deciding an incident is material.",
        source: "Federal Computer-Security Incident Notification Rule; NYDFS Part 500; SEC Form 8-K Item 1.05",
      },
      {
        region: "us",
        title: "The FFIEC assessment tool has been withdrawn",
        text: "The FFIEC withdrew its Cybersecurity Assessment Tool on 31 August 2025 and pointed banks to NIST CSF 2.0 and the Cybersecurity Performance Goals from CISA, the US Cybersecurity and Infrastructure Security Agency.",
        source: "FFIEC statement on the Cybersecurity Assessment Tool",
      },
    ],
    helps: [
      {
        icon: "shield",
        title: "Regulator rules as owned controls",
        text: "The SOC 2 library ships today. Add a control for each regulator requirement it does not cover, such as an SBP circular, give it an owner and attach evidence with a renewal date. Libraries for SBP, CBUAE, APRA and NYDFS rules are coming soon.",
        modules: ["compliance-automation", "evidence-management"],
      },
      {
        icon: "handshake",
        title: "An outsourcing register that stays current",
        text: "Record each vendor and every engagement with it, and tier each engagement on five questions, including business criticality and regulatory scope. The twelve-stage lifecycle runs from intake to offboarding, and the approval gate holds while any critical finding is open.",
        modules: ["third-party-risk"],
      },
      {
        icon: "siren",
        title: "Short deadlines, tracked in hours",
        text: "Record an incident as an issue in Tasks, with containment, corrective and preventive actions, each with an owner. Raise the regulator notification as a task on a service level set in hours, so a missed deadline shows and escalates. Incident records arrive with enterprise risk, coming soon.",
        modules: ["workflows-and-approvals", "enterprise-risk-management"],
      },
      {
        icon: "chart",
        title: "Board figures from live records",
        text: "The compliance dashboard and each module's overview read from your own data: readiness by criterion, open findings by severity, vendors by tier and service-level breaches. The controls, risk, asset and vulnerability registers export to a spreadsheet. The executive dashboard is a preview with illustrative figures, and key risk indicators are coming soon.",
        modules: ["compliance-automation", "risk-management", "enterprise-risk-management"],
      },
    ],
    frameworks: [
      "sbp-etgrmf",
      "cbuae-operational-risk-regulation",
      "apra-cps-234",
      "nydfs-part-500",
      "sbp-outsourcing-framework",
      "cbuae-outsourcing-regulation",
      "apra-cps-230",
      "sbp-cloud-outsourcing-framework",
      "iso-27001",
      "nist-csf-2",
      "swift-cscf",
      "pci-dss",
      "sbp-payment-card-security",
      "sec-cyber-disclosure",
    ],
    workflow: {
      title: "Prepare for a regulator's IT inspection",
      intro: "How a bank's IT risk and compliance teams could use Verity in the months before an IT inspection. Every step uses features that are live today.",
      steps: [
        { title: "Give every control an owner", text: "Start from the SOC 2 library, add controls for your regulator's requirements, and assign each one to a named owner or a team." },
        { title: "Collect evidence that stays fresh", text: "Attach each artefact once to every control it proves. Its type sets a validity period, and the register shows what has gone stale before an inspector finds it." },
        { title: "Review material outsourcing", text: "Tier each vendor engagement, send due-diligence questionnaires through the vendor portal, and keep contracts and SOC 2 reports on file with their expiry dates." },
        { title: "Track findings to closure", text: "Raise each gap as a task or issue with an owner, a due date and a service level. Closure can require an approver, and every transition is recorded." },
        { title: "Open a window for inspectors", text: "Invite inspectors or external auditors as guest auditors with access start and end dates. Outside that window they cannot sign in, and the audit log records every change." },
      ],
    },
    roles: [
      "Chief Information Security Officer",
      "Chief Risk Officer",
      "Heads of operational risk and IT risk",
      "Head of Compliance",
      "Chief Internal Auditor",
      "Outsourcing and vendor management office",
      "Secretaries of the board risk and IT committees",
    ],
    faqs: [
      {
        q: "Does Verity cover the State Bank of Pakistan's frameworks today?",
        a: "Not as a ready-made library yet. Libraries for SBP frameworks, including the ETGRMF and the outsourcing and cloud frameworks, are coming soon. Today you can add a control for each requirement, give it an owner and map evidence to it, alongside the SOC 2 library that ships now.",
      },
      {
        q: "Can we keep our outsourcing register in Verity?",
        a: "Yes, as the vendor register. Each engagement with a vendor is tiered on five questions, including business criticality and regulatory scope, and the record holds the owners, where the data lives and the contracts with their expiry dates. Verity files nothing with a regulator; your institution does.",
      },
      {
        q: "Can we report to the board from Verity?",
        a: "From live data, yes. The compliance dashboard and the overview tabs on risks, vendors, vulnerabilities and tasks read from your own records, and the controls, risk, asset and vulnerability registers export to a spreadsheet. The executive dashboard is a preview with illustrative figures, and key risk indicators are coming soon.",
      },
      {
        q: "Can a central bank use Verity for its own programme?",
        a: "Yes. A central bank has its own controls, IT risks, suppliers and policies, and Verity organises them in a sealed workspace like any other organisation's. It is not a supervisory system: no screen or export shows data from two workspaces together, so it cannot be used to oversee the institutions you regulate.",
      },
    ],
  },
  {
    slug: "fintech-payments",
    eyebrow: "Fintech and payments",
    headline: "Answer regulators and partner banks from one set of records",
    lead: "Payment providers, wallets and digital lenders face their regulator's technology rules, card-data requirements and due-diligence questionnaires from partner banks. Verity keeps controls, evidence, policies, vendors and remediation in one connected workspace, so the proof gathered for one request is ready for the next.",
    audiences: [
      "Payment system operators and payment service providers",
      "Electronic money institutions and digital wallets",
      "Payment processors and merchant acquirers",
      "Digital lenders",
      "Fintechs that partner with banks",
    ],
    obligations: [
      {
        region: "pk",
        title: "SBP technology risk framework for payment institutions",
        text: "Payment system operators, payment service providers and electronic money institutions had to comply with the State Bank of Pakistan's Technology Risk Management Framework for Payment Institutions by 31 March 2026.",
        source: "SBP PSP&OD Circular No. 04 of 2025",
      },
      {
        region: "ae",
        title: "Cyber risk frameworks and open finance in the UAE",
        text: "Payment service providers licensed by the Central Bank of the UAE must run a technology and cyber security risk management framework. CBUAE licensees must also join the Open Finance framework, published in April 2024 and being phased in.",
        source: "CBUAE Retail Payment Services and Card Schemes Regulation (Circular No. 15/2021); CBUAE Open Finance framework",
      },
      {
        region: "au",
        title: "Report ransomware payments within 72 hours",
        text: "Since 30 May 2025, businesses with an annual turnover above A$3 million must report any ransomware or cyber extortion payment to the Australian Signals Directorate within 72 hours.",
        source: "Cyber Security Act 2024 (Cth)",
      },
      {
        region: "us",
        title: "A written security programme and 30-day FTC notice",
        text: "Non-bank fintechs covered by the FTC Safeguards Rule need a written information security programme, including multi-factor authentication and encryption, and must notify the FTC within 30 days of discovering a breach affecting 500 or more consumers.",
        source: "FTC Safeguards Rule, 16 CFR Part 314",
      },
      {
        region: "global",
        title: "Future-dated PCI DSS requirements are now mandatory",
        text: "Organisations that store, process or transmit payment card data are assessed against PCI DSS v4.0.1, published by the PCI Security Standards Council. Its future-dated requirements became mandatory on 31 March 2025.",
        source: "PCI DSS v4.0.1",
      },
    ],
    helps: [
      {
        icon: "seal",
        title: "One set of controls, many reviews",
        text: "Partner banks commonly ask for a SOC 2 report, and the SOC 2 library ships with every workspace. Add your own controls for SBP's payment-institution framework or any other rule, and attach evidence once to every control it proves. More libraries, including PCI DSS, are coming soon.",
        modules: ["compliance-automation", "evidence-management"],
      },
      {
        icon: "file",
        title: "A written programme, approved and read",
        text: "Start from 15 policy templates, including access control, cryptography and incident response. Route each through approval tiers, publish it, and run an acknowledgement campaign to show who read which version. Mapped to controls, a policy stands as evidence.",
        modules: ["policy-management"],
      },
      {
        icon: "handshake",
        title: "Watch the providers you depend on",
        text: "Cloud hosts, card processors and identity-verification providers often hold your customers' data. Tier each engagement, send questionnaires through the vendor portal, track findings to their due dates, and keep contracts, data processing agreements and SOC 2 reports with their expiry dates.",
        modules: ["third-party-risk"],
      },
      {
        icon: "bug",
        title: "Fix what matters, on time",
        text: "Import scanner exports, tie each finding to the asset it sits on, and rank it by known exploitation and the asset's criticality, not CVSS alone. Each finding gets a remediation window from its severity, and exceptions need an approver and an expiry.",
        modules: ["vulnerability-management", "asset-inventory"],
      },
    ],
    frameworks: [
      "sbp-trmf-payment-institutions",
      "pci-dss",
      "soc-2",
      "cbuae-operational-risk-regulation",
      "au-privacy-act",
      "glba-safeguards-rule",
      "sbp-payment-card-security",
      "iso-27001",
      "cbuae-consumer-protection",
      "apra-cps-234",
      "nydfs-part-500",
      "sbp-cloud-outsourcing-framework",
      "essential-eight",
      "uae-pdpl",
    ],
    workflow: {
      title: "Get ready for a partner bank's review",
      intro: "How a payment company's small security and compliance team could prepare for a partner bank's due diligence, using only features that are live today.",
      steps: [
        { title: "Start from the SOC 2 library", text: "Every workspace begins with the SOC 2 controls adopted. Set your audit scope, assign owners, and add controls for your regulator's requirements." },
        { title: "Publish your core security policies", text: "Draft from the policy templates, take each through approval tiers, publish it and run an acknowledgement campaign so every signature is on record." },
        { title: "Connect GitHub for daily checks", text: "Seven checks read your repositories every day, such as branch protection and required reviews, and attach dated results to the controls they support." },
        { title: "Review your critical providers", text: "Tier your processors and cloud hosts, send questionnaires through the vendor portal, and keep their SOC 2 reports and contracts with expiry dates." },
        { title: "Close gaps before the review", text: "Raise each gap as a task with an owner, a due date and a service level. Readiness on the compliance dashboard climbs as controls are implemented with evidence." },
      ],
    },
    roles: [
      "Founder or CTO",
      "Head of Compliance, often also the money-laundering reporting officer",
      "CISO or Head of Security",
      "Head of Risk",
      "Payments operations",
      "Partnership teams answering banks' due-diligence questionnaires",
    ],
    faqs: [
      {
        q: "Does Verity cover the State Bank of Pakistan's framework for payment institutions?",
        a: "Not as a ready-made library yet; it is coming soon. Today you can add a control for each of its requirements, give each an owner and attach evidence, alongside the SOC 2 library that ships with every workspace. Evidence attaches to controls, not to a framework, so the work carries forward.",
      },
      {
        q: "Will Verity get us a SOC 2 report or PCI DSS compliance?",
        a: "No. Reports and compliance validations come from independent auditors and assessors. Verity organises the controls, evidence, policies and decisions they review, and shows your SOC 2 readiness as you go. The PCI DSS library is coming soon.",
      },
      {
        q: "Can we answer a bank's security questionnaire in Verity?",
        a: "Not automatically yet. Questionnaire automation, which will suggest answers from your controls, policies and evidence for a person to approve, is coming soon. The records it will draw on are live today, and sending questionnaires to your own vendors through the vendor portal is live now.",
      },
      {
        q: "We are a small team. Where do we start?",
        a: "With the Get Started checklist, which tracks your real setup progress. The quickest route: give your controls owners, invite your people, import your asset and vendor spreadsheets and attach your first evidence. Then connect GitHub.",
      },
    ],
  },
  {
    slug: "healthcare",
    eyebrow: "Healthcare",
    headline: "Show how you protect patient data, whenever you are asked",
    lead: "Hospitals, clinics, payers and health-technology companies answer to health regulators and privacy law, and technology suppliers also face their customers' vendor reviews. Verity keeps controls, evidence, policies, vendors and systems in one connected record, so a risk analysis or an audit starts from what you already hold.",
    audiences: [
      "Hospitals and health systems",
      "Clinics, laboratories and diagnostic centres",
      "Health insurers and payers",
      "Health-technology companies",
      "Suppliers that handle health data for providers",
    ],
    obligations: [
      {
        region: "ae",
        title: "ADHICS v2.0 is mandatory in Abu Dhabi",
        text: "The Abu Dhabi Healthcare Information and Cyber Security Standard is mandatory for healthcare facilities, payers and health-technology providers that handle health information in Abu Dhabi. Version 2.0 took effect in August 2024, replacing the 2019 standard.",
        source: "Department of Health – Abu Dhabi, ADHICS v2.0",
      },
      {
        region: "ae",
        title: "Health data kept in the UAE, for at least 25 years",
        text: "Health data must be stored and processed inside the UAE unless an exception in Ministerial Resolution No. 51 of 2021 applies, and must be kept for at least 25 years.",
        source: "UAE Federal Law No. 2 of 2019 (Health ICT Law)",
      },
      {
        region: "au",
        title: "Privacy law at any size; some hospitals are critical assets",
        text: "The Privacy Act covers health service providers whatever their turnover. A suspected eligible data breach must be assessed within 30 days and notified as soon as practicable. Hospitals with a general intensive care unit are critical infrastructure assets under the SOCI Act.",
        source: "Privacy Act 1988 (Cth); Security of Critical Infrastructure Act 2018",
      },
      {
        region: "us",
        title: "HIPAA safeguards, 60-day breach notices and a pending update",
        text: "Covered entities and business associates must perform a risk analysis, apply the HIPAA safeguards and notify breaches within 60 days of discovery. A major Security Rule update proposed in January 2025 was still not final in mid-2026, so organisations are planning around rules that may change.",
        source: "HIPAA Security Rule and Breach Notification Rule (45 CFR Parts 160 and 164)",
      },
      {
        region: "pk",
        title: "Cybercrime law applies; data protection is still a draft",
        text: "The Prevention of Electronic Crimes Act 2016, amended in 2025, applies to health organisations as to any other. The Personal Data Protection Bill was approved by the Federal Cabinet in July 2023 but had not been enacted by mid-2026.",
        source: "PECA 2016 (amended 2025); Personal Data Protection Bill (draft)",
      },
    ],
    helps: [
      {
        icon: "shield",
        title: "One control set for many rulebooks",
        text: "Health systems often ask their technology suppliers for HITRUST certification. The SOC 2 library ships today; libraries for ADHICS, HIPAA and HITRUST are coming soon. Until then, add controls of your own for each requirement and attach the evidence that proves them.",
        modules: ["compliance-automation", "evidence-management"],
      },
      {
        icon: "scales",
        title: "A risk analysis that stays current",
        text: "List the systems that hold health data, rate each for confidentiality, integrity and availability, and let Verity derive its criticality. Record risks against them with inherent and residual scores, treatment plans, and acceptances that carry an approver and an expiry.",
        modules: ["asset-inventory", "risk-management"],
      },
      {
        icon: "handshake",
        title: "Suppliers who touch patient data",
        text: "Record every supplier that holds or reaches health data, including where the data lives, and tier each engagement. Send due-diligence questionnaires through the vendor portal, track findings to closure, and keep contracts, including business associate agreements, and certificates with their expiry dates.",
        modules: ["third-party-risk"],
      },
      {
        icon: "file",
        title: "Policies staff have actually read",
        text: "Start from 15 policy templates, including access control, data management and incident response. Route each through approval tiers and publish it. Acknowledgement campaigns target people, roles or groups, such as a clinic team, and record who signed which version and when.",
        modules: ["policy-management"],
      },
    ],
    frameworks: [
      "adhics",
      "hipaa-security-rule",
      "au-privacy-act",
      "uae-health-ict-law",
      "iso-27001",
      "hitrust-csf",
      "pk-peca",
      "iso-27701",
      "soci-act-cirmp",
      "essential-eight",
      "nist-csf-2",
      "soc-2",
      "pk-pdpb",
    ],
    workflow: {
      title: "Get ready for a patient-data security audit",
      intro: "How a hospital's information security and privacy team could prepare for an audit of how patient data is protected, using only features that are live today.",
      steps: [
        { title: "Map where patient data lives", text: "Import your asset list, record each system's data classification and owners, rate confidentiality, integrity and availability, and add the dependencies between clinical systems." },
        { title: "Score the risks to it", text: "Record risks against those systems in a register with your own matrix, score inherent and residual risk, link the controls that reduce each one, and track treatment as tasks." },
        { title: "Publish policies, collect signatures", text: "Take your access control and data management policies and incident response plan through approval, publish them, and ask every department to acknowledge them." },
        { title: "Review suppliers that hold records", text: "Tier each supplier engagement, send questionnaires through the vendor portal, and keep contracts and certificates with expiry dates, so lapses show before they happen." },
        { title: "Give the auditor a dated window", text: "Invite the auditor as a guest with access start and end dates. Evidence shows its freshness, and every change sits in an audit log nobody can edit." },
      ],
    },
    roles: [
      "CISO or Head of Information Security",
      "Privacy officer or data protection officer",
      "Health information management lead",
      "CIO or Chief Medical Information Officer",
      "Quality and compliance teams",
      "Internal audit",
      "Vendor-risk teams at payers",
    ],
    faqs: [
      {
        q: "Does Verity include ADHICS, HIPAA or HITRUST today?",
        a: "Not yet. Those libraries are coming soon, and the SOC 2 library ships with every workspace today. Until then you can add a control for each requirement you work to, give it an owner and attach evidence, and keep your risk analysis in the live risk register.",
      },
      {
        q: "Can we run a HIPAA risk analysis in Verity?",
        a: "You can do the work in live modules: list the systems that hold health data in the asset inventory, record and score risks against them, and link the controls and tasks that treat them. Whether the analysis meets the rule is for your team and advisers to judge.",
      },
      {
        q: "UAE health data generally has to stay in the country. Where would our evidence be held?",
        a: "Verity holds evidence about your controls, such as configuration exports, policies and signed reviews, not clinical records, so keep patient data out of evidence files. Talk to us about hosting and data-residency requirements before you start.",
      },
      {
        q: "Does Verity certify us?",
        a: "No. Certifications such as HITRUST, and attestation reports such as SOC 2, are issued by independent assessors and auditors, and regulators run their own audits. Verity organises the controls, evidence and decisions they review.",
      },
    ],
  },
  {
    slug: "saas-technology",
    eyebrow: "SaaS and technology",
    headline: "Ready for SOC 2, and for the security reviews that follow",
    lead: "Enterprise customers usually ask for a SOC 2 Type II report, and regulated ones add questionnaires and data-residency questions. Verity ships the SOC 2 control library on day one, keeps evidence fresh across your observation window and runs daily checks on your GitHub organisation.",
    audiences: [
      "SaaS companies selling to enterprises",
      "Cloud hosting and managed service providers",
      "Software suppliers to banks and insurers",
      "Suppliers to government and defence",
      "Companies building AI products",
    ],
    obligations: [
      {
        region: "pk",
        title: "Pakistani bank customers need approval for offshore cloud",
        text: "Banks regulated by the State Bank of Pakistan need its approval to run material workloads on offshore cloud, so expect data-residency questions in due diligence. Federal public-sector buyers apply the five-tier data classification in the Cloud First Policy 2022.",
        source: "SBP BPRD Circular No. 01 of 2023; Cloud First Policy 2022",
      },
      {
        region: "ae",
        title: "DESC certification to serve the Dubai Government",
        text: "Cloud providers serving Dubai Government and semi-government entities must be certified against the Dubai Electronic Security Center's CSP Security Standard. Its Information Security Regulation v3.0 bars storing or processing critical government information outside the UAE.",
        source: "DESC CSP Security Standard; DESC ISR v3.0",
      },
      {
        region: "au",
        title: "IRAP for government, APRA duties passed down by customers",
        text: "Government buyers rely on IRAP assessments against the Information Security Manual. APRA-regulated customers must manage material service providers under CPS 230 and assess third parties' security capability under CPS 234, so expect those questions in their reviews.",
        source: "ASD IRAP; APRA CPS 230 and CPS 234",
      },
      {
        region: "us",
        title: "FedRAMP and CMMC for US federal and defence work",
        text: "Cloud services sold to US federal agencies need FedRAMP authorisation, and its Consolidated Rules for 2026 set a move from Rev5 to the 20x model. CMMC requirements have appeared in Department of Defense contracts since 10 November 2025.",
        source: "FedRAMP Consolidated Rules for 2026; CMMC (32 CFR Part 170)",
      },
      {
        region: "us",
        title: "California cybersecurity audits from April 2028",
        text: "The largest businesses covered by the CCPA must certify cybersecurity audits from 1 April 2028, under regulations from the California Privacy Protection Agency that took effect on 1 January 2026.",
        source: "CCPA regulations (California Privacy Protection Agency)",
      },
      {
        region: "eu",
        title: "EU AI Act duties arriving in stages",
        text: "Obligations for general-purpose AI models have applied since August 2025. Most high-risk obligations were deferred to 2 December 2027 (Annex III) and 2 August 2028 (Annex I). ISO/IEC 42001 offers a certifiable AI management system.",
        source: "EU AI Act, Regulation (EU) 2024/1689, as amended",
      },
    ],
    helps: [
      {
        icon: "seal",
        title: "SOC 2 from day one",
        text: "Every workspace starts with the SOC 2 library adopted: 61 criteria mapped to 114 control templates. Set your scope and observation window, give each control an owner, and watch readiness by criterion as evidence lands. Your auditor issues the report.",
        modules: ["compliance-automation", "evidence-management"],
      },
      {
        icon: "plug",
        title: "Daily checks on your code platform",
        text: "Connect GitHub with a read-only token and seven checks run daily, attaching dated evidence to the controls they support. A broken connection shows as an error, never a failed control. Cloud and identity connections and continuous monitoring are coming soon.",
        modules: ["integrations", "continuous-monitoring"],
      },
      {
        icon: "handshake",
        title: "Your own suppliers, reviewed in proportion",
        text: "Regulated customers ask about the suppliers behind you. Tier each supplier engagement, send due-diligence questionnaires through the vendor portal, and keep their SOC 2 reports and data processing agreements with expiry dates. Answering customers' questionnaires from your records, and a Trust Center, are coming soon.",
        modules: ["third-party-risk", "questionnaire-automation", "trust-center"],
      },
      {
        icon: "bug",
        title: "Vulnerabilities fixed inside the window",
        text: "Import scanner exports, match each finding to the asset it sits on, and rank it by known exploitation, exploit likelihood and the asset's criticality, not CVSS alone. Remediation windows follow severity, and an exception needs an approver and an expiry date.",
        modules: ["vulnerability-management", "asset-inventory"],
      },
    ],
    frameworks: [
      "soc-2",
      "iso-27001",
      "gdpr",
      "sbp-cloud-outsourcing-framework",
      "desc-csp-security-standard",
      "apra-cps-230",
      "fedramp",
      "iso-27018",
      "ccpa-cpra",
      "hipaa-security-rule",
      "iso-42001",
      "eu-ai-act",
      "irap",
      "cmmc-2",
    ],
    workflow: {
      title: "Prepare for a first SOC 2 Type II audit",
      intro: "How a software company's security lead and engineers could move from an adopted library to an audit-ready observation window, using only features that are live today.",
      steps: [
        { title: "Set scope and the window", text: "Name the engagement, choose Type II, set the observation window and pick the Trust Services categories you are claiming. Security is always in scope." },
        { title: "Give every control an owner", text: "Filter the controls register by Owner: None and assign each control to a person or a group, so nothing is left unowned." },
        { title: "Connect GitHub for daily evidence", text: "Seven checks run daily against your repositories and attach dated results, so your change controls have evidence across the whole window." },
        { title: "Publish policies and get signatures", text: "Draft from the policy templates, route each through approval, publish, and run acknowledgement campaigns so you can show who read which version." },
        { title: "Give the auditor a window", text: "Invite your auditor as a guest with access dates. Evidence carries its freshness, and every change sits in an append-only audit log." },
      ],
    },
    roles: [
      "CTO or VP of Engineering",
      "CISO or Head of Security",
      "GRC or compliance manager",
      "Customer-trust and sales-engineering teams",
      "Data protection officer or privacy counsel",
    ],
    faqs: [
      {
        q: "Can Verity get us a SOC 2 report?",
        a: "No. An independent auditor examines your controls and issues the report. Verity organises the controls, evidence, policies and decisions they review, shows your readiness against the scope you set, and gives the auditor a time-boxed login.",
      },
      {
        q: "Do you support ISO/IEC 27001 as well as SOC 2?",
        a: "SOC 2 ships today. The ISO/IEC 27001 library is coming soon and is planned to reuse the controls you already operate, so evidence collected once counts for both. Until then, add controls of your own for any Annex A requirement SOC 2 does not cover.",
      },
      {
        q: "Which systems can Verity connect to today?",
        a: "GitHub, with seven checks that run every day. Connections for cloud providers such as AWS, Azure and Google Cloud, identity providers such as Okta and Microsoft Entra ID, and ticketing tools such as Jira are coming soon. Until then, add evidence as files or links.",
      },
      {
        q: "Can Verity answer our customers' security questionnaires?",
        a: "Not yet. Questionnaire automation, which will suggest answers from your controls, policies and evidence for a person to approve, is coming soon, as is the Trust Center. Sending questionnaires to your own suppliers through the vendor portal is live today.",
      },
    ],
  },
  {
    slug: "government-public-sector",
    eyebrow: "Government and public sector",
    headline: "Information assurance you can evidence, year after year",
    lead: "Ministries, agencies and regulators work to national cyber security policies and control baselines, report to oversight bodies, and rely on suppliers who must meet the same rules. Verity keeps controls, evidence, policies, risks, suppliers and systems in one sealed workspace, with every change in an audit log nobody can edit.",
    audiences: [
      "Ministries, departments and divisions",
      "Government agencies and statutory authorities",
      "Regulators, for their own programmes",
      "Dubai Government and semi-government entities",
      "Australian Government entities",
      "Public bodies that run critical infrastructure",
    ],
    obligations: [
      {
        region: "pk",
        title: "A national cyber security policy and five data classes",
        text: "Pakistan's National Cyber Security Policy 2021 calls for computer emergency response teams and security operations centres, protection of critical information infrastructure, and an audit and compliance framework for information assurance. The Cloud First Policy 2022 sorts federal data into five classes.",
        source: "National Cyber Security Policy 2021 (MoITT); Cloud First Policy 2022",
      },
      {
        region: "ae",
        title: "DESC ISR v3.0 for Dubai Government entities",
        text: "Dubai Government entities follow the Dubai Electronic Security Center's Information Security Regulation v3.0. It requires a UAE national to lead information security and bars storing or processing critical government information outside the UAE. Cloud providers serving them must be certified against DESC's CSP Security Standard.",
        source: "DESC ISR v3.0; DESC CSP Security Standard",
      },
      {
        region: "au",
        title: "Essential Eight Maturity Level Two and yearly reporting",
        text: "Since 1 July 2022, non-corporate Commonwealth entities must implement the Essential Eight to Maturity Level Two. They must also appoint a Chief Security Officer and a CISO, and report each year under the Protective Security Policy Framework; Release 2026 is current.",
        source: "PSPF Release 2026 (Department of Home Affairs)",
      },
      {
        region: "au",
        title: "An Information Security Manual updated every quarter",
        text: "The Australian Signals Directorate updates the Information Security Manual every quarter; the September 2026 release is the latest. Government buyers rely on IRAP assessments made against it.",
        source: "ASD Information Security Manual; IRAP",
      },
      {
        region: "us",
        title: "NIST SP 800-53, FedRAMP and CMMC set the baselines",
        text: "Federal agencies and their cloud providers work from NIST SP 800-53 Rev. 5, now at release 5.2.0 from August 2025, and FedRAMP. Defence contractors handling controlled unclassified information implement NIST SP 800-171 and are assessed under CMMC.",
        source: "NIST SP 800-53 Rev. 5; FedRAMP; NIST SP 800-171; CMMC",
      },
    ],
    helps: [
      {
        icon: "shield",
        title: "Your baseline as owned controls",
        text: "Add a control for each requirement in your baseline, whether a DESC ISR clause or a PSPF requirement, give it an owner and attach evidence with a renewal date. Libraries for Essential Eight, UAE IA, DESC ISR and NIST SP 800-53 are coming soon.",
        modules: ["compliance-automation", "evidence-management"],
      },
      {
        icon: "stamp",
        title: "Policies approved in the right order",
        text: "Approval runs in tiers: a named person, a role or a group at each tier, with tier two opening only when tier one clears. Published policies are never deleted, and acknowledgement campaigns record who in each department signed which version.",
        modules: ["policy-management"],
      },
      {
        icon: "handshake",
        title: "Supplier assurance in proportion to risk",
        text: "Requests for new suppliers go through intake, with duplicate screening, before anything enters the register. Tiering sets how deep diligence goes, the approval gate holds while critical findings are open, and the person requesting approval cannot grant it.",
        modules: ["third-party-risk"],
      },
      {
        icon: "scales",
        title: "Risk decisions that keep their reasons",
        text: "Keep separate registers with their own matrices, score inherent and residual risk, and link the controls that treat each one. Accepting a risk needs a second person and an expiry date, and a lapsed acceptance reopens the risk on its own.",
        modules: ["risk-management"],
      },
    ],
    frameworks: [
      "pspf",
      "desc-isr",
      "nist-sp-800-53",
      "iso-27001",
      "essential-eight",
      "uae-ia-standard",
      "pk-peca",
      "australian-ism",
      "fedramp",
      "nist-sp-800-171",
      "cmmc-2",
      "nist-csf-2",
      "irap",
      "desc-csp-security-standard",
    ],
    workflow: {
      title: "Prepare for an annual assurance review",
      intro: "How an agency's information security team could gather a year's evidence for an audit or an annual assurance report, using only features that are live today.",
      steps: [
        { title: "Set out your control baseline", text: "Reuse the shipped SOC 2 controls where they fit, add your own for the rest, and give each an owner or owning group." },
        { title: "Know your systems and owners", text: "Import your asset list, rate each system for confidentiality, integrity and availability, record its data classification, and review records on a cadence set by criticality." },
        { title: "Keep evidence current all year", text: "Attach evidence once to every control it proves. Validity periods flag stale proof, and a reviewer accepts each item or rejects it with a reason." },
        { title: "Track weaknesses to closure", text: "Import scanner findings, prioritise by known exploitation and asset criticality, and hold each to a remediation window. Exceptions need an approver and an expiry date." },
        { title: "Give auditors a dated window", text: "Invite auditors as guests with access start and end dates. Outside the window they cannot sign in, and every change is in the append-only audit log." },
      ],
    },
    roles: [
      "Agency CISO",
      "Chief Security Officer",
      "Chief Information Officer",
      "Information assurance and accreditation teams",
      "Risk and audit committees",
      "Procurement and supplier-assurance teams",
    ],
    faqs: [
      {
        q: "Does Verity include the PSPF, Essential Eight or UAE IA today?",
        a: "Not yet. Those libraries are coming soon, along with DESC ISR and NIST SP 800-53. Today the SOC 2 library ships with every workspace, and you can add your own controls for any requirement, assign owners and attach evidence.",
      },
      {
        q: "Where would our data be held?",
        a: "Rules differ by government: DESC ISR v3.0, for example, bars storing or processing critical government information outside the UAE. Talk to us about hosting and data-residency requirements before you start. Within the platform, each workspace is sealed by the database itself on every query.",
      },
      {
        q: "Does Verity prepare our annual report or accreditation?",
        a: "No. Verity organises the controls, evidence, risks and decisions behind them. Your organisation prepares and submits its own reports, and independent assessors or auditors carry out assessments. Verity submits nothing on your behalf.",
      },
      {
        q: "What happens to the record when staff move on?",
        a: "Disable the membership rather than deleting it. The person loses access at once, and their name stays on the approvals they gave and the evidence they collected. The audit log is append-only and cannot be edited, even by an administrator.",
      },
    ],
  },
];
