import type { Metadata } from "next";
import Link from "next/link";
import { CtaPair } from "@/components/cta-pair";
import { LandingIntro } from "@/components/landing-intro";
import { ComplianceVisual, SecurityVisual, VendorVisual } from "@/components/home-visuals";
import { HeroGraph, ModuleIcon, type PlatformArea } from "@/components/hero-graph";
import { CoverageMap } from "@/components/coverage-map";
import { DemoBookingForm } from "@/components/demo-booking-form";
import { getSiteConfig } from "@/lib/site-config";

export const metadata: Metadata = { alternates: { canonical: "/" } };

const capabilities = [
  { kind: "compliance", title: "Compliance", text: "Turn requirements into owned controls and see the evidence behind each one.", href: "/docs/03-frameworks-and-controls/", label: "CONTROL RECORD", record: "Logical access review", meta: "SOC 2 · CC6.1", rows: [["Owner", "Security team"], ["Evidence", "Access review attached"], ["Status", "In review"]] },
  { kind: "risk", title: "Risk", text: "Score exposure, assign treatment, and keep acceptance decisions on record.", href: "/docs/07-risks/", label: "RISK REGISTER", record: "Privileged access", meta: "Treatment in progress", rows: [["Owner", "IT operations"], ["Response", "Mitigate"], ["Review", "Due this quarter"]] },
  { kind: "vendors", title: "Third parties", text: "Manage intake, questionnaires, assessments, approvals, and ongoing review.", href: "/docs/08-vendors/", label: "VENDOR ENGAGEMENT", record: "Cloud service review", meta: "Assessment stage", rows: [["Tier", "High"], ["Questionnaire", "Received"], ["Decision", "Pending review"]] },
  { kind: "audits", title: "Evidence and reviews", text: "Collect proof, check its quality, and follow findings back to their controls.", href: "/docs/04-evidence/", label: "EVIDENCE RECORD", record: "Quarterly access review", meta: "Linked to 2 controls", rows: [["Source", "Uploaded file"], ["Reviewer", "Compliance lead"], ["Decision", "Awaiting review"]] },
  { kind: "assets", title: "Assets and vulnerabilities", text: "Keep an inventory and work findings through ownership and remediation.", href: "/docs/09-assets/", label: "ASSET RECORD", record: "Customer portal", meta: "Production application", rows: [["Criticality", "High"], ["Finding", "1 open"], ["Owner", "Platform team"]] },
  { kind: "policies", title: "Policies and documents", text: "Draft, approve, publish, and track acknowledgements in one lifecycle.", href: "/docs/05-policies-and-documents/", label: "POLICY RECORD", record: "Access control policy", meta: "Published version", rows: [["Approver", "Security lead"], ["Next review", "Scheduled"], ["Mapping", "Access controls"]] },
];

function CapabilityArt({ item }: { item: (typeof capabilities)[number] }) {
  return <span className="capability-art" aria-hidden="true"><span className="capability-art-top"><span>{item.label}</span><span className="capability-art-dot" /></span><span className="capability-art-record"><strong>{item.record}</strong><small>{item.meta}</small></span><span className="capability-art-rows">{item.rows.map(([label, value]) => <span key={label}><span>{label}</span><b>{value}</b></span>)}</span></span>;
}

export default function HomePage() {
  const { trialUrl } = getSiteConfig();
  return <>
    <LandingIntro />
    <main id="main-content" className="v2-home">
      <section className="v2-hero" aria-labelledby="hero-heading">
        <div className="site-container v2-hero-inner"><div className="v2-hero-copy">
          <p className="v2-eyebrow">ONE CONNECTED GRC PLATFORM</p>
          <h1 id="hero-heading" tabIndex={-1}>Everything in your GRC program, connected.</h1>
          <p className="v2-hero-lead">Controls, risks, evidence, vendors, assets, and reviews work together, so your team can see what needs attention and why.</p>
          <CtaPair demoHref="#request-demo" />
          <p className="v2-hero-note">SOC 2 control content is available now. Additional frameworks are planned.</p>
        </div><HeroGraph /></div>
      </section>

      <section id="approach" className="v2-intro-section" aria-labelledby="approach-title"><div className="site-container v2-intro-grid"><div><span className="v2-eyebrow">WHY VERITY</span><h2 id="approach-title">Compliance depends on work happening across your company.</h2></div><div><p>Controls alone do not tell you whether a program is ready. You need the evidence, affected assets, open risks, vendor decisions, and accountable people behind them.</p><p>Verity gives that work a clear place to live and a history you can follow.</p></div></div></section>

      <section id="platform" className="v2-product-index" aria-labelledby="product-index-title"><div className="site-container"><div className="v2-index-heading"><span className="v2-eyebrow">THE PLATFORM</span><h2 id="product-index-title">A place for every part of the program.</h2><p>Open a record, see its owner and status, and follow the work connected to it. These examples show how the modules fit together.</p></div><div className="v2-capability-grid">{capabilities.map((item) => <Link href={item.href} className={`v2-capability-card capability-${item.kind}`} key={item.title}><span className="v2-capability-icon"><ModuleIcon area={item.kind as PlatformArea} /></span><strong>{item.title}</strong><span className="capability-description">{item.text}</span><CapabilityArt item={item} /><span className="v2-card-link">Read the guide</span></Link>)}</div></div></section>

      <section id="compliance" className="v2-feature-section" aria-labelledby="compliance-title"><div className="site-container v2-feature-grid"><div className="v2-feature-copy"><span className="v2-eyebrow">COMPLIANCE MANAGEMENT</span><h2 id="compliance-title">From requirement to evidence, without losing the thread.</h2><p>Adopt a control, give it an owner, and see the requirement and evidence that belong to it. Reviews and decisions remain on the record.</p><ul><li>Map tenant controls to framework requirements</li><li>Collect and review linked evidence</li><li>Track ownership, tasks, and activity history</li></ul><Link className="v2-text-link" href="/docs/03-frameworks-and-controls/">Explore controls and frameworks</Link></div><ComplianceVisual /></div></section>

      <section id="security" className="v2-feature-section v2-feature-alt" aria-labelledby="security-title"><div className="site-container v2-feature-grid"><SecurityVisual /><div className="v2-feature-copy"><span className="v2-eyebrow">SECURITY OPERATIONS</span><h2 id="security-title">Know what is exposed and who is fixing it.</h2><p>Assets anchor vulnerability findings. Teams can prioritize a finding, assign remediation, and follow it through review.</p><ul><li>Maintain an asset inventory</li><li>Import and triage vulnerability findings</li><li>Follow remediation by severity and owner</li></ul><Link className="v2-text-link" href="/docs/10-vulnerabilities/">Explore vulnerability management</Link></div></div></section>

      <section id="risk" className="v2-feature-section" aria-labelledby="risk-title"><div className="site-container v2-feature-grid"><div className="v2-feature-copy"><span className="v2-eyebrow">RISK AND THIRD PARTIES</span><h2 id="risk-title">Bring the decision into the same record as the review.</h2><p>Vendor engagements have a lifecycle. Risk registers have treatments and acceptance decisions. Verity keeps those steps visible to the people responsible for them.</p><ul><li>Assess vendor engagements and record findings</li><li>Track risk ownership and treatment</li><li>Retain decision reasons and history</li></ul><Link className="v2-text-link" href="/docs/08-vendors/">Explore vendor reviews</Link></div><VendorVisual /></div></section>

      <section id="coverage" className="v2-map-section" aria-labelledby="map-title"><div className="site-container"><div className="v2-centered-heading"><span className="v2-eyebrow">CONNECTED CONTEXT</span><h2 id="map-title">Trace the record behind a decision.</h2><p>Choose an area to see how a requirement, control, asset, finding, and decision can relate. The records shown here are examples.</p></div><CoverageMap /></div></section>

      <section id="trust" className="v2-governance-section" aria-labelledby="trust-title"><div className="site-container"><div className="v2-centered-heading"><span className="v2-eyebrow">GOVERNANCE</span><h2 id="trust-title">Built for accountable decisions.</h2><p>Verity keeps access and record history close to the work your teams manage.</p></div><div className="v2-governance-grid"><div><span className="governance-symbol">01</span><h3>Tenant boundaries</h3><p>Each customer workspace is isolated in the application and database access path.</p></div><div><span className="governance-symbol">02</span><h3>Role based access</h3><p>Permissions, assignments, and object scope determine who may act on a record.</p></div><div><span className="governance-symbol">03</span><h3>Auditable changes</h3><p>Changes and review decisions retain the actor and the record history.</p></div><div><span className="governance-symbol">04</span><h3>Human review</h3><p>Suggested mappings and AI drafts require a person to approve them.</p></div></div><div className="v2-framework-note"><strong>Available now</strong><span>SOC 2 control content and the workflows in the public guide.</span><strong>On the roadmap</strong><span>Additional framework libraries and business continuity. VantageMDM is separate software.</span></div></div></section>

      <section className="v2-docs-section" aria-labelledby="docs-title"><div className="site-container v2-docs-grid"><div><span className="v2-eyebrow">DOCUMENTATION</span><h2 id="docs-title">See how the work gets done.</h2><p>The public guide walks through setup, controls, evidence, assets, risks, vendors, and administration with task instructions and product images.</p><Link className="button button-outline" href="/docs/">Open documentation</Link></div><nav aria-label="Documentation topics" className="v2-docs-links"><Link href="/docs/01-getting-started/"><span>01</span>Getting started</Link><Link href="/docs/03-frameworks-and-controls/"><span>02</span>Controls and requirements</Link><Link href="/docs/04-evidence/"><span>03</span>Evidence reviews</Link><Link href="/docs/08-vendors/"><span>04</span>Vendor engagements</Link></nav></div></section>

      <section className="v2-faq-section" aria-labelledby="faq-title"><div className="site-container v2-faq-grid"><div><span className="v2-eyebrow">COMMON QUESTIONS</span><h2 id="faq-title">Questions before you begin?</h2><p>Details that matter when evaluating a GRC platform.</p></div><div className="v2-faq-list"><details><summary>Which frameworks can we use today?</summary><p>The shipped content library is SOC 2. The platform models frameworks and requirements so more libraries can be added, but ISO 27001 content is not available yet.</p></details><details><summary>Can we manage security work as well as compliance?</summary><p>Yes. Assets, vulnerabilities, risks, vendor engagements, policies, tasks, controls, and evidence each have workflows in Verity. The <Link href="/docs/">user guide</Link> shows current screens.</p></details><details><summary>How do integrations work?</summary><p>GitHub is the first live connector. Teams can also work directly in Verity, including uploading evidence and importing findings. Other connectors shown as “Soon” are planned.</p></details><details><summary>Is business continuity or VantageMDM included?</summary><p>Business continuity is planned for Verity. VantageMDM is separate software and is not an integrated Verity module today.</p></details><details><summary>How do we book a demo?</summary><p>You can explore the form and choose a preferred date below. Booking is a preview and does not send your details or reserve a time yet.</p></details></div></div></section>

      <section id="request-demo" className="v2-demo-section" aria-labelledby="demo-title"><div className="site-container v2-demo-grid"><div><span className="v2-eyebrow">SEE VERITY</span><h2 id="demo-title">Tell us what your team needs to bring together.</h2><p>Choose the areas you want to discuss and a preferred date. Booking is being connected, so this preview does not send a request yet.</p><div className="v2-demo-callout"><strong>Ready to explore on your own?</strong><p>Go to the Verity app to start a trial.</p><a className="button button-dark" href={trialUrl}>Start trial</a></div></div><DemoBookingForm /></div></section>
    </main>
  </>;
}
