"""Write docs/architecture/check-catalogue.md from the shipped content.

The map an auditor follows, requirement to control to test to system to evidence, for every
criterion and every connector and Verity module, generated from the same JSON the product loads
so the document cannot drift from it::

    cd backend
    python scripts/build_check_catalogue.py
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "src" / "verity" / "seed" / "content"
OUT = ROOT.parent / "docs" / "architecture" / "check-catalogue.md"

_CADENCE = {
    "annual": "yearly",
    "quarterly": "quarterly",
    "monthly": "monthly",
    "on_change": "on change",
    "per_event": "per event",
    "once": "once",
    "ongoing": "ongoing",
}


def _load(pack: str, name: str) -> list[dict]:
    return json.loads((CONTENT / pack / name).read_text(encoding="utf-8"))


def _state(check: dict, capabilities: dict[str, dict]) -> str:
    """What a workspace can have of this check today, by catalogue alone."""
    if check["implementations"]:
        return "running once connected"
    states = []
    for key in check["capabilities"]:
        best = "not planned"
        for provider in capabilities[key]["providers"]:
            if provider["status"] in ("available", "planned"):
                best = "planned"
        states.append(best)
    return "not planned" if "not planned" in states else "planned"


def _systems(check: dict, capabilities: dict[str, dict]) -> str:
    parts = []
    for key in check["capabilities"]:
        names = [p["name"] for p in capabilities[key]["providers"]]
        shown = ", ".join(names[:4]) + (f" and {len(names) - 4} more" if len(names) > 4 else "")
        parts.append(f"{capabilities[key]['name']} ({shown})")
    return "; ".join(parts)


def main() -> None:
    templates = {t["code"]: t for t in _load("soc2", "control_templates.json")}
    requirements = _load("soc2", "requirements.json")
    mappings = _load("soc2", "template_requirements.json")
    checks = _load("automation", "checks.json")
    capabilities = {c["key"]: c for c in _load("automation", "capabilities.json")}

    by_control: dict[str, list[dict]] = defaultdict(list)
    for check in checks:
        for link in check["controls"]:
            by_control[link["code"]].append({**check, "link": link})
    by_criterion: dict[str, list[dict]] = defaultdict(list)
    for mapping in mappings:
        by_criterion[mapping["requirement_key"]].append(mapping)

    lines = [
        "# Check catalogue: requirement to control to test to evidence",
        "",
        "Generated by `backend/scripts/build_check_catalogue.py` from `seed/content`.",
        "Do not edit by hand.",
        "",
        f"{len(requirements)} SOC 2 criteria, {len(templates)} controls, {len(checks)} tests, "
        f"{len(capabilities)} capabilities. A test says which kind of system it needs, never one "
        "vendor; one connected system per kind is enough. **Running once connected** means a "
        "collector ships today (GitHub). **Planned** means the systems are in the delivery plan "
        "and no collector exists yet, so the control page says people provide the evidence for "
        "now. Verity (built in) tests read Verity's own modules and are planned until their "
        "runner ships. The mappings are Verity's reading and are not yet reviewed by a second "
        "person.",
        "",
        "## Tests",
        "",
        "| Test | Needs | Collects | Controls (coverage) | State |",
        "|---|---|---|---|---|",
    ]
    for check in sorted(checks, key=lambda c: c["key"]):
        controls = ", ".join(f"{m['code']} ({m['coverage']})" for m in check["controls"])
        lines.append(
            f"| `{check['key']}` {check['name']} | {_systems(check, capabilities)} | "
            f"{'; '.join(check['evidence_kinds'])} | {controls} | {_state(check, capabilities)} |"
        )

    lines += ["", "## By criterion", ""]
    for requirement in requirements:
        key = requirement["requirement_key"]
        rows = by_criterion[key]
        lines += [
            f"### {requirement['code']}  ({requirement['trust_services_category']})",
            "",
            requirement["name"],
            "",
        ]
        for mapping in sorted(rows, key=lambda m: m["template_code"]):
            code = mapping["template_code"]
            template = templates[code]
            lines.append(
                f"- **{code} {template['name']}** ({mapping['coverage']}). {mapping['rationale']}"
            )
            for check in sorted(by_control[code], key=lambda c: c["key"]):
                collects = "; ".join(check["evidence_kinds"]).lower()
                lines.append(
                    f"  - test `{check['key']}` ({check['link']['coverage']}, "
                    f"{_state(check, capabilities)}): collects {collects}"
                )
            for item in template["evidence"]:
                route = (
                    f"Verity {item['module']}"
                    if item["source"] == "platform"
                    else "provided by people"
                )
                auto = (
                    f", collected by {', '.join(f'`{k}`' for k in item['automated_by'])}"
                    if item.get("automated_by")
                    else ""
                )
                lines.append(
                    f"  - evidence: {item['name']} ({item['assurance']}, "
                    f"{_CADENCE[item['cadence']]}, {route}{auto})"
                )
        lines.append("")
    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
