import {
  ArrowRight,
  ArrowUpRight,
  Bank,
  Bell,
  BookOpenText,
  Brain,
  Briefcase,
  Bug,
  Buildings,
  CalendarCheck,
  CaretDown,
  CaretRight,
  Certificate,
  ChartBar,
  ChartDonut,
  ChartLineUp,
  ChatCircleText,
  Check,
  CheckCircle,
  CircleDashed,
  ClipboardText,
  Clock,
  Cloud,
  Code,
  Compass,
  Copy,
  CreditCard,
  Cube,
  Database,
  Desktop,
  Detective,
  Envelope,
  Eye,
  FileText,
  Fingerprint,
  FirstAid,
  Flag,
  Folder,
  Funnel,
  Gauge,
  GearSix,
  GlobeHemisphereWest,
  GraduationCap,
  Graph,
  Handshake,
  HardDrives,
  Hash,
  Heartbeat,
  IdentificationCard,
  Info,
  Kanban,
  Key,
  Laptop,
  Lightbulb,
  Lifebuoy,
  Lightning,
  LinkSimple,
  List,
  ListChecks,
  LockKey,
  MagnifyingGlass,
  MapTrifold,
  Moon,
  Path,
  Plugs,
  Pulse,
  RocketLaunch,
  Scales,
  Scroll,
  SealCheck,
  ShieldCheck,
  ShieldWarning,
  Signature,
  Siren,
  Sparkle,
  Stack,
  Stamp,
  Storefront,
  Sun,
  Target,
  ThumbsDown,
  ThumbsUp,
  TreeStructure,
  TrendUp,
  UserCheck,
  UserGear,
  UsersThree,
  User,
  Vault,
  Warning,
  X,
} from "@phosphor-icons/react/dist/ssr";

/**
 * One icon family across the site, and the same family as the Verity product
 * (Phosphor), so recreated product screens read as the real thing.
 */
const icons = {
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  bank: Bank,
  bell: Bell,
  book: BookOpenText,
  brain: Brain,
  briefcase: Briefcase,
  bug: Bug,
  building: Buildings,
  calendar: CalendarCheck,
  "caret-down": CaretDown,
  "caret-right": CaretRight,
  certificate: Certificate,
  chart: ChartBar,
  donut: ChartDonut,
  "chart-line": ChartLineUp,
  chat: ChatCircleText,
  "check-plain": Check,
  check: CheckCircle,
  "circle-dashed": CircleDashed,
  clipboard: ClipboardText,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  compass: Compass,
  copy: Copy,
  "credit-card": CreditCard,
  cube: Cube,
  database: Database,
  desktop: Desktop,
  detective: Detective,
  envelope: Envelope,
  eye: Eye,
  file: FileText,
  fingerprint: Fingerprint,
  "first-aid": FirstAid,
  flag: Flag,
  folder: Folder,
  funnel: Funnel,
  gauge: Gauge,
  gear: GearSix,
  globe: GlobeHemisphereWest,
  graduation: GraduationCap,
  graph: Graph,
  handshake: Handshake,
  server: HardDrives,
  hash: Hash,
  heartbeat: Heartbeat,
  id: IdentificationCard,
  info: Info,
  kanban: Kanban,
  key: Key,
  laptop: Laptop,
  lightbulb: Lightbulb,
  lifebuoy: Lifebuoy,
  lightning: Lightning,
  link: LinkSimple,
  menu: List,
  list: ListChecks,
  lock: LockKey,
  search: MagnifyingGlass,
  map: MapTrifold,
  moon: Moon,
  path: Path,
  plug: Plugs,
  pulse: Pulse,
  rocket: RocketLaunch,
  scales: Scales,
  scroll: Scroll,
  seal: SealCheck,
  shield: ShieldCheck,
  "shield-warning": ShieldWarning,
  signature: Signature,
  siren: Siren,
  sparkle: Sparkle,
  stack: Stack,
  stamp: Stamp,
  store: Storefront,
  sun: Sun,
  target: Target,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  tree: TreeStructure,
  trend: TrendUp,
  "user-check": UserCheck,
  "user-gear": UserGear,
  users: UsersThree,
  user: User,
  vault: Vault,
  warning: Warning,
  x: X,
};

export type IconName = keyof typeof icons;

export const iconNames = Object.keys(icons) as IconName[];

export function isIconName(value: string): value is IconName {
  return value in icons;
}

type Weight = "thin" | "light" | "regular" | "bold" | "fill" | "duotone";

export function Icon({ name, size = 20, weight = "regular", className, label }: { name: IconName; size?: number; weight?: Weight; className?: string; label?: string }) {
  const Glyph = icons[name];
  return label ? (
    <Glyph size={size} weight={weight} className={className} role="img" aria-label={label} />
  ) : (
    <Glyph size={size} weight={weight} className={className} aria-hidden="true" focusable="false" />
  );
}
