"""user email verification and terms

Revision ID: 68050122d7e5
Revises: 8f2c5d1b9a47
Create Date: 2026-08-13 11:37:23.705179

Two nullable columns on the global ``users`` table: ``email_verified_at`` (NULL
until the work email is confirmed via the signup link; an unverified user gets no
session) and ``terms_accepted_at`` (when the account holder accepted Terms &
Privacy at signup). ``users`` is identity-plane — no ``tenant_id``, no RLS.
Downgrade drops both columns, discarding every recorded verification and
acceptance timestamp.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "68050122d7e5"
down_revision: str | None = "8f2c5d1b9a47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("email_verified_at", postgresql.TIMESTAMP(timezone=True), nullable=True)
    )
    op.add_column(
        "users", sa.Column("terms_accepted_at", postgresql.TIMESTAMP(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "terms_accepted_at")
    op.drop_column("users", "email_verified_at")
    # ### end Alembic commands ###
